### ISSUE TITLE
Сыпет ошибку

### ISSUE THREAD

**Issue by WowExotic** [kainlighty/LightCheck#13]
### Plugin Version

2.2.0

### Select The Core

Paper

### Description

Сыпет такую ошибку и по какой-то причине циклично выдает бан игроку до тех пор, пока плагин не перезагрузишь

[22:58:39] [Server thread/WARN]: [LightCheck] Task #306579 for LightCheck v2.2.0 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at ru.kainlight.lightcheck.UTILS.Runnables.stopMessages(Runnables.java:38) ~[LightCheck.jar:?]
	at ru.kainlight.lightcheck.UTILS.Runnables.stopAll(Runnables.java:52) ~[LightCheck.jar:?]
	at ru.kainlight.lightcheck.API.CheckedPlayer.approve(CheckedPlayer.java:35) ~[LightCheck.jar:?]
	at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$1(Runnables.java:75) ~[LightCheck.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by kainlighty** [comment]
После чего именно?

**Comment by WowExotic** [comment]
> После чего именно?

Поставили игрока на проверку, у него багнулся интернет и его выкинуло, после этого циклично шел бан

**Comment by kainlighty** [comment]
Перекачай плагин, вроде должно исправиться. По сути, если игрока именно кикает, не должно такого быть

**Comment by WowExotic** [comment]
> Перекачай плагин, вроде должно исправиться. По сути, если игрока именно кикает, не должно такого быть

Хорошо, это посмотрим. Сейчас я искуственно создаю ситуацию лива при помощи разрыва соединения с сервером и в таком случае наказание за лив не выдается при выходе самого проверяющего, если он вышел до проверяемого

**Comment by kainlighty** [comment]
что?

**Comment by kainlighty** [comment]
Причем тут проверяющий, изначально речь шла о проверяемом

**Comment by kainlighty** [comment]
Если во время проверки вышел проверяющий, то проверяемый не наказывается, все верно. По написанной тобой проблеме как?

**Comment by WowExotic** [comment]
> Причем тут проверяющий, изначально речь шла о проверяемом

Есть контакт в каком нибудь мессенджере?

**Comment by kainlighty** [comment]
на гитхабе в профиле ссылка

**Comment by WowExotic** [comment]
> на гитхабе в профиле ссылка

А есть дс или тг?

**Comment by kainlighty** [comment]
> > на гитхабе в профиле ссылка
> 
> А есть дс или тг?

@kansought
