### ISSUE TITLE
Ошибка при /lightcheck stop-all

### ISSUE THREAD

**Issue by KatanaSq209** [kainlighty/LightCheck#15]
### Plugin Version

Plugin 2.0.7 | Minecraft 1.16.5 16+ java

### Select The Core

Paper

### Description

Полная консоль в:
t-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:47 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:47 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:48 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:48 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:49 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:49 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:50 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:50 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:51 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:51 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:52 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:52 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:53 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 54771
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[18:54:53 WARN]: [LightCheck] Plugin LightCheck v2.0.7 generated an exception while executing task 22200
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "timerValue" is null
        at ru.kainlight.lightcheck.UTILS.Runnables.lambda$startTimerScheduler$0(Runnables.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
        
Написал /lightcheck stop-all
При использовании команды написано еще An internal ocured error и так далее!
В чем проблема?

**Comment by kainlighty** [comment]
Привет!

Возможно, таймер либо закончился, либо был остановлен.

Вижу, ты используешь 1.16.5, скорее всего, на новых версиях такой ошибки не будет.

Извини, сейчас нет времени потестировать и исправить. Как будет, посмотрю.

**Comment by kainlighty** [comment]
Привет!

Этой ошибки нет на новых версиях плагина. 

Понимаю, 1.16 всё еще остается юзабельна, но поддерживать версии ниже сейчас не могу. Используй, пожалуйста, новую версию.
